### ISSUE TITLE
Create upstream repo for your prelim on arfc

### ISSUE THREAD

**Issue by munkm** [samgdotson/2023-dotson-prelim#1]
I'm glad you have your prelim repository ready to go! I think it would be great to have it on the arfc group as well, since your work is important to the group! Would you mind creating an upstream repo for your prelim there?

**Comment by katyhuff** [comment]
@samgdotson -- please do this. Also, please create a dissertation repo in arfc if there isn't one yet. Thanks.

**Comment by samgdotson** [comment]
I forked this on the ARFC org -- does this resolve the issue? @katyhuff
